POST http://localhost:8081/cloud/login
accept: */*
Content-Type: application/json

{
  "login": "user",
  "password": "31234"
}

###

GET http://localhost:8081/cloud/list?limit=1
accept: application/json


###

GET http://localhost:8081/cloud/file?filename=fff
accept: multipart/form-data
