###
POST http://localhost:8080/cloud/login
accept: */*
Content-Type: application/json

{
  "login": "string",
  "password": "string"
}


###
POST http://localhost:8080/cloud/logout
accept: */*
auth-token: ttt


###
POST http://localhost:8080/cloud/file?filename=filename
accept: */*
auth-token: ttt
Content-Type: multipart/form-data


###
DELETE http://localhost:8080/cloud/file?filename=filename
accept: */*
auth-token: ttt


###
GET http://localhost:8080/cloud/file?filename=filename
accept: multipart/form-data

###
PUT http://localhost:8080/cloud/file?filename=filename
accept: */*
auth-token: ttt
Content-Type: application/json

{
  "name" : "string"
}

###
GET http://localhost:8080/cloud/list?limit=5
accept: application/json
auth-token: ttt

