server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diplom
    username: root
    password: 31234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true